### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xelm#1]
Launch Checklist

In order to launch we should have:

- [x] Elm as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] At least 10 problems
- [x] Documentation (see below)
- [x] One to a handful of people willing to check exercism regularly (daily?) to review. This will ensure that the track gets off on the right foot.
- [x] Add track implementors and other designated code reviewers as mentors to the track. This gives you access to all the solutions in Elm whether or not you've submitted the problem to the site.
- [x] Toggle `"active"` to `true` in `config.json`
- [x] Mention it in the next "behind the scenes" email (noted)

## Documentation

The documentation lives in the `docs/` directory here in this repository, and gets served to the site via the x-api. It should contain at minimim:

- `INSTALLATION.md` - about how to get the language set up locally.
- `TESTS.md` - about how to run the tests for the exercises.

Some nice to haves:

- `ABOUT.md` - a short, friendly blurb about the language. What types of problems does it solve really well? What is it typically used for?
- `LEARNING.md` - a few notes about where people might want to go to learn the language from scratch.
- `RESOURCES.md` - references and other useful resources.

## Successful Launches

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by parkerl** [comment]
@kytrinyx is anyone working on elm exercises?

**Comment by kytrinyx** [comment]
No, I haven't heard anything in a long time.

**Comment by parkerl** [comment]
@kytrinyx this looks like this task no longer applies?
- [ ] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-elm.md`)

**Comment by tgecho** [comment]
I've reached out a bit to the elm mailing list / slack channel, and there seems to be a bit of interest. Nothing so strong as a commitment to mentor yet. I need to find a bit more info on he mechanics of that. I'll obviously pitch in, but the whole reason I showed up here was to get my own code nitpicked!

**Comment by kytrinyx** [comment]
@parkerl Oops. Yeah, it should now be the various `docs/` things.

**Comment by kytrinyx** [comment]
@parkerl I've updated the initial post here to reflect the new launch checklist.

**Comment by tgecho** [comment]
@parkerl @kytrinyx I think we've pretty much covered all of the bases apart from the [active flag](https://github.com/exercism/xelm/pull/41) and signing up a few core mentors. In the mean time, it seems like it would make sense to soft launch the new track exercises ([x-api PR](https://github.com/exercism/x-api/pull/103)) so we can make sure everything looks decent and also so we have something to show interested Elmers.

**Comment by parkerl** [comment]
@kytrinyx :fire: in the hole?!?

**Comment by kytrinyx** [comment]
It's live, you can `exercism fetch elm $SLUG`. I'm getting on a plane (again) in about four hours. I probably won't deploy the x-api again until Tuesday morning, even if the active flag gets switched earlier (@parkerl you've got commit. Do you want deploy on x-api as well? Cause then you could launch the track whenever you're ready)

**Comment by parkerl** [comment]
@kytrinyx I'd be happy to deploy but I also think we can be patient. Hope travel is more of a straight line this time.

**Comment by kytrinyx** [comment]
I got home in under 40 hours! Almost miraculous. Thanks for being patient. I'll be deploying this tomorrow (I don't trust myself at the moment; just walked in the door at home).

**Comment by kytrinyx** [comment]
We are live!
